[fix] Exporting inner tags
storytouch/ep_align pull request #5
Opened 2020-06-09 15:16 UTC by ingoncalves

This PR fixes the case when a line with alignment has styles, such as bold, italic, underline. The previous implementation did not allow us to export these tags to HTML.

Implements part of the [card 2237](https://trello.com/c/FrbBtWRx).

2020-06-09 15:51 UTC, joassouza requested changes
Bom PR! 
Podemos conversar dp no #devs essa questão da ordem e evitar o `<p>`.
Vamos usar essa mesma lógica aqui para um monte de coisa, teremos que processar comments, tags...Muito bom ter que mexer nisso

2020-06-09 15:51 UTC, joassouza commented on index.js
> +};
esse cara é um elemento de ui do editor. A gente pode remover isso e o template. Tem remover `ep_align/templates/editbarButtons.ejs`

2020-06-09 15:51 UTC, joassouza commented on index.js
> +    context.lineContent = "<p style='text-align:" + alignment + "'>" + replaceGeneralTag(lineContent) + "</p>";
aqui talvez a gente poderia exportar somente uma `<general>` ou `<elemento>` ao invés de <p>. Os atributos `text-align` são atributos de linha. Como resultado a gente teria algo pre-pronto
`<general style='text-align:stuff'>texto aqui</general>`.
Talvez o que esteja acontecendo é que o ep_se tá processando ANTES, então adiciona a tag e depois vem isso daí fica uma dentro de outra.

2020-06-09 15:51 UTC, joassouza commented on index.js
> +function replaceGeneralTag(lineContent) {
se der certo o que comentei a gente n precisa disso

2020-06-09 15:51 UTC, joassouza commented on index.js
>  // line, apool,attribLine,text
a coisa tá meio complexa, seria bom adicionar os testes disso aqui. Embora a gente quase não rode (vergonha 🤦 ), a gente tem um plano de começar rodar esse cara.

2020-06-09 22:13 UTC, ingoncalves commented on index.js
> +};
Esses caras são usados nos testes nativos do componente. Se removermos vamos ter que refatorar todos os testes. O que acha?

2020-06-09 22:14 UTC, ingoncalves commented on index.js
>  // line, apool,attribLine,text
Testes de backend ainda não existem neste plugin. Depois me dá um help pra gente criar.

2020-06-10 14:09 UTC, joassouza commented on index.js
>  // line, apool,attribLine,text
É ruim a gente postergar teste, mas de repente podemos implementar quando a gente mudar a forma de exportação para fazer chamadas via API

2020-06-10 14:32 UTC, merged